/**
 * Draws the frame SVGs for every generated Yâsîn sheet.
 *
 *     npm run emit:frames
 *
 * Each frame gets its OWN file, drawn at the exact aspect it is displayed at.
 * That is not fussiness: an SVG plane in this project is stretched to
 * (scaleX, scaleY) world units, so a shared 1:1 file on a 0.55-aspect frame
 * arrives with oval corners and a rim half as thick down the sides as across
 * the top. Every hand-made frame in /public says so in its own header; this
 * script is how the generated ones get the same treatment.
 *
 *   viewBox height is always 1000, width = 1000 · (w / h)
 *   → one SVG unit = h / 1000 world units on BOTH axes
 *
 * so a world-unit rim or radius converts with the same factor either way.
 *
 * The four paints are lifted from the hand-made frames, byte for byte:
 *   outer  gold rim + opaque panel      /yasin1319/all-section.svg
 *   band   blue #CEE0E9 @ 0.60          /yasin1319/band.svg
 *   inner  lavender #E1E3F3 @ 0.85      /yasin1319/band-inner.svg
 *   ring   cream #F5EEDC @ 0.60         /yasin/ring-outer.svg
 */

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { YASIN_SHEETS } from "../app/data/configs/yasin/sheets";
import type { FrameTone } from "../app/data/configs/yasin/kit";

// Resolved off the working directory, not `__dirname`: the script runs from
// its compiled copy under .frames-build, so `__dirname` is not in the repo.
const PUBLIC_DIR = join(process.cwd(), "public");

/** World-unit rim thickness every frame in this family is drawn at. */
const RIM_WORLD = 0.0088;
/** World-unit rim of the solid outer frame — thinner, it is a rim not a rule. */
const OUTER_RIM_WORLD = 0.0042;

const GOLD_STOPS = `
<stop stop-color="#968428"/>
<stop offset="0.503741" stop-color="#CDC577"/>
<stop offset="1" stop-color="#968428"/>`;

/**
 * `stadium` frames take fully rounded ends — the onion the handwritten sheets
 * draw around a chiasm (ayahs 28 … 32), and the shape of /yasin/ring-*.svg.
 * The rest are rounded rectangles.
 */
const PAINTS: Record<
  Exclude<FrameTone, "outer">,
  { fill: string; opacity: number; stadium?: boolean; lens?: boolean; ellipse?: boolean }
> = {
  rose: { fill: "#F3DEDE", opacity: 0.55 },
  band: { fill: "#CEE0E9", opacity: 0.6 },
  inner: { fill: "#E1E3F3", opacity: 0.85 },
  ring: { fill: "#F5EEDC", opacity: 0.6, stadium: true },
  ringMid: { fill: "#E1E3F3", opacity: 0.7, stadium: true },
  ringInner: { fill: "#CEE0E9", opacity: 0.75, stadium: true },
  // The 33-36 sheet is drawn as a rosette: four LENS petals (two arcs meeting
  // at a point, like /yasin/leaf.svg) inside one big CIRCLE.
  lens: { fill: "#EDF3EA", opacity: 0.55, lens: true },
  circle: { fill: "#DCE9F2", opacity: 0.45, ellipse: true },
};

function svgFor(tone: FrameTone, w: number, h: number, id: string): string {
  const vbH = 1000;
  const vbW = Math.round((1000 * w) / h);
  const unit = h / 1000; // world units per SVG unit, both axes
  // Corner radius: 9% of the short side, the proportion band.svg uses — or
  // half of it for a stadium, which is where the rounded ends come from.
  const short = Math.min(vbW, vbH);
  const radius =
    tone !== "outer" && PAINTS[tone].stadium ? short / 2 : short * 0.09;
  const grad = `${id}Gold`;
  const defs = `<defs>
<linearGradient id="${grad}" x1="0" y1="${vbH / 2}" x2="${vbW}" y2="${vbH / 2}" gradientUnits="userSpaceOnUse">${GOLD_STOPS}
</linearGradient>
</defs>`;

  const head = `<svg width="${vbW}" height="${vbH}" viewBox="0 0 ${vbW} ${vbH}" fill="none" xmlns="http://www.w3.org/2000/svg" shape-rendering="geometricPrecision">
<!-- GENERATED by scripts/emitSheetFrames.ts — edit the sheet declaration in
     app/data/sheets/yasinSheets.ts and re-run, or edit this file by hand and
     stop regenerating it. Drawn at the aspect it is displayed at:
       world ${w.toFixed(3)} x ${h.toFixed(3)}  ->  ${(w / h).toFixed(3)}
       viewBox ${vbW} x ${vbH}  ->  ${(vbW / vbH).toFixed(3)}
     one SVG unit = ${unit.toExponential(3)} world units on both axes. -->
${defs}`;

  if (tone === "outer") {
    const rim = Math.max(2, Math.round(OUTER_RIM_WORLD / unit));
    return `${head}
<rect x="0" y="0" width="${vbW}" height="${vbH}" rx="${radius.toFixed(1)}" ry="${radius.toFixed(1)}" fill="url(#${grad})"/>
<rect x="${rim}" y="${rim}" width="${vbW - rim * 2}" height="${vbH - rim * 2}" rx="${(radius - rim).toFixed(1)}" ry="${(radius - rim).toFixed(1)}" fill="#F0E4E5"/>
</svg>
`;
  }

  const paint = PAINTS[tone];
  const sw = Math.max(2, Math.round(RIM_WORLD / unit));

  // A LENS is two quadratic arcs meeting at the left and right points — the
  // mandorla the handwritten 33-36 sheet draws each ayah inside. An ELLIPSE is
  // the ring that holds all four of them.
  if (paint.lens) {
    const i = sw / 2;
    return `${head}${defs}
<path d="M ${i} ${vbH / 2} Q ${vbW / 2} ${i} ${vbW - i} ${vbH / 2} Q ${vbW / 2} ${vbH - i} ${i} ${vbH / 2} Z"
      fill="${paint.fill}" fill-opacity="${paint.opacity}"
      stroke="url(#${grad})" stroke-width="${sw}" stroke-linejoin="round"/>
</svg>
`;
  }
  if (paint.ellipse) {
    return `${head}${defs}
<ellipse cx="${vbW / 2}" cy="${vbH / 2}" rx="${vbW / 2 - sw / 2}" ry="${vbH / 2 - sw / 2}"
      fill="${paint.fill}" fill-opacity="${paint.opacity}"
      stroke="url(#${grad})" stroke-width="${sw}"/>
</svg>
`;
  }
  return `${head}
<rect x="${sw / 2}" y="${sw / 2}" width="${vbW - sw}" height="${vbH - sw}"
      rx="${radius.toFixed(1)}" ry="${radius.toFixed(1)}"
      fill="${paint.fill}" fill-opacity="${paint.opacity}"
      stroke="url(#${grad})" stroke-width="${sw}"/>
</svg>
`;
}

let written = 0;
for (const [key, sheet] of Object.entries(YASIN_SHEETS)) {
  sheet.frames.forEach((frame, i) => {
    const out = join(PUBLIC_DIR, frame.src);
    mkdirSync(dirname(out), { recursive: true });
    writeFileSync(
      out,
      svgFor(frame.tone, frame.w, frame.h, `${key}F${i}`),
      "utf8",
    );
    written++;
    console.log(
      `${frame.src.padEnd(30)} ${frame.tone.padEnd(6)} ${frame.w.toFixed(3)} x ${frame.h.toFixed(3)}`,
    );
  });
}
console.log(`\n${written} frame(s) written.`);
